name: Build_plugin

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build plugin
      run: ./build.sh
    - uses: actions/upload-artifact@master
      with:
        name: rundeck-nginxplus-upstream-plugin.zip
        path: build/rundeck-nginxplus-upstream-plugin.zip
